# Generated by Django 4.1.3 on 2022-12-03 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseproduct',
            name='price',
            field=models.FloatField(),
        ),
    ]
