# Generated by Django 4.1.3 on 2022-12-02 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_selectedwarehouse'),
        ('cart', '0003_alter_cartproduct_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='warehouse',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse'),
            preserve_default=False,
        ),
    ]
