# Generated by Django 4.1.3 on 2022-12-15 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse_product', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=256)),
                ('city', models.CharField(default='', max_length=128)),
                ('status', models.CharField(choices=[('PLACED', 'Placed'), ('FAILED', 'Failed'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('DELIVERED', 'Delivered'), ('ON_THE_WAY', 'On the way'), ('PACKED', 'Packed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=64)),
                ('payment_method', models.CharField(choices=[('COD', 'COD'), ('CARD', 'CARD')], default='COD', max_length=64)),
                ('card_number', models.CharField(blank=True, default='', max_length=16, null=True)),
                ('savings', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cart_amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('payment_completed', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('total_items', models.IntegerField(default=0)),
                ('delivery_date', models.CharField(default='', max_length=64)),
                ('delivery_time', models.CharField(choices=[('8', '8:00 AM to 10:00 AM'), ('10', '10:00 AM to 12:00 PM'), ('12', '12:00 PM to 14:00 PM'), ('14', '14:00 PM to 16:00 PM'), ('16', '16:00 PM to 18:00 PM')], default='8', max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('warehouse_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_product.warehouseproduct')),
            ],
        ),
    ]
