# Generated by Django 4.1.3 on 2023-01-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'COD'), ('CARD', 'CARD'), ('WALLET', 'WALLET')], default='COD', max_length=64),
        ),
    ]
